### PR TITLE
Include Firefox version and channel in reports (closes #23).

### LINKED ISSUE #23: Reports should include Firefox version and channel.
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/system#build
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/system#version

### PR DESCRIPTION
**Pull request by chuckharmston**

### CODE REVIEW

**Comment by chuckharmston** [comment]
Updated to accommodate 7b5e503.

**Review by lmorchard — APPROVED** [review]
:+1:

**Comment by meandavejustice** [comment]
Should there be an default case in `channel.js` to catch fork builds like iceweasel or palemoon?

**Comment by chuckharmston** [comment]
> Should there be an default case in channel.js to catch fork builds like iceweasel or palemoon?

The default case is `RELEASE`, so the only reason to do this would be for total accuracy. Since there are likely no users out there who are trying to run Test Pilot experiments on those builds, I'm not too concerned about getting one or two of those numbers right.

**Pull request merged**
