### PR TITLE
Prepares for deployment to S3.

### PR DESCRIPTION
**Pull request by chuckharmston**

### CODE REVIEW

**Review by meandavejustice — APPROVED** [review]
Looks good 2 me

**Comment by meandavejustice** [comment]
I believe the next step will be to have setup at `production` branch

**Comment by lmorchard** [comment]
Yeah, need to set up a `production` branch and then work with @relud & @clouserw to get the Jenkins infra setup.

**Comment by chuckharmston** [comment]
Already done!

I'm technically PTO today but it'll be out on production soon.

**Comment by relud** [comment]
@chuckharmston already worked with me to get the jenkins infra set up

**Pull request merged**
